version: '3.8'

services:

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    build: .
    restart: always
    ports:
      - "8079:8079"
    depends_on:
      - db
    environment:
      - API_KEY_NASA=${API_KEY_NASA}
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=5432
    volumes:
      - .:/app
      - air_config:/root/.air
volumes:
  pgdata:
  air_config:
